/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Action = Action1;
export type Reversible = boolean;

export interface Action1 {
  reversible?: Reversible;
  [k: string]: unknown;
}
