/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AddDirectory = AddDirectory1;
export type Path = string;

export interface AddDirectory1 {
  path: Path;
  [k: string]: unknown;
}
