/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AddFile = AddFile1;
export type Filepath = string;
export type Content = string;

export interface AddFile1 {
  filepath: Filepath;
  content: Content;
  [k: string]: unknown;
}
