/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CallGraph = CallGraph1;
export type FunctionName = string;
export type Filepath = string;
export type Line = number;
export type Character = number;
export type Calls = CallGraph1[];

/**
 * A call graph of a function.
 */
export interface CallGraph1 {
  function_name: FunctionName;
  function_range: RangeInFile;
  calls: Calls;
}
export interface RangeInFile {
  filepath: Filepath;
  range: Range;
}
/**
 * A range in a file. 0-indexed.
 */
export interface Range {
  start: Position;
  end: Position;
}
export interface Position {
  line: Line;
  character: Character;
}
