/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DebugContext = SerializedDebugContext;
export type Traceback = string;
export type Filepath = string;
export type Line = number;
export type Character = number;
export type RangesInFiles = RangeInFile[];
export type Description = string;

export interface SerializedDebugContext {
  traceback: Traceback;
  ranges_in_files: RangesInFiles;
  filesystem: Filesystem;
  description: Description;
  [k: string]: unknown;
}
export interface RangeInFile {
  filepath: Filepath;
  range: Range;
}
/**
 * A range in a file. 0-indexed.
 */
export interface Range {
  start: Position;
  end: Position;
}
export interface Position {
  line: Line;
  character: Character;
}
export interface Filesystem {
  [k: string]: string;
}
