/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DeleteFile = DeleteFile1;
export type Filepath = string;

export interface DeleteFile1 {
  filepath: Filepath;
  [k: string]: unknown;
}
