/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DeleteDirectory = DeleteDirectory1;
export type Path = string;

export interface DeleteDirectory1 {
  path: Path;
  [k: string]: unknown;
}
