/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EditDiff = EditDiff1;

/**
 * A reversible edit that can be applied to a file.
 */
export interface EditDiff1 {
  forward: FileSystemEdit;
  backward: FileSystemEdit;
  [k: string]: unknown;
}
export interface FileSystemEdit {
  [k: string]: unknown;
}
