/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type History = History1;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Output = [Observation, Action];
export type Reversible = boolean;
export type Timeline = HistoryNode[];
export type CurrentIndex = number;

/**
 * A history of actions taken
 */
export interface History1 {
  timeline: Timeline;
  current_index: CurrentIndex;
  [k: string]: unknown;
}
/**
 * A node in a DAG
 */
export interface HistoryNode {
  step: Step;
  output?: Output;
  [k: string]: unknown;
}
export interface Step {
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
export interface Action {
  reversible?: Reversible;
  [k: string]: unknown;
}
