/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HistoryNode = HistoryNode1;
/**
 * @minItems 2
 * @maxItems 2
 */
export type Output = [Observation, Action];
export type Reversible = boolean;

/**
 * A node in a DAG
 */
export interface HistoryNode1 {
  step: Step;
  output?: Output;
  [k: string]: unknown;
}
export interface Step {
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
export interface Action {
  reversible?: Reversible;
  [k: string]: unknown;
}
