/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HistoryNode = HistoryNode1;
export type Name = string;
export type Hide = boolean;

/**
 * A point in history, a list of which make up History
 */
export interface HistoryNode1 {
  step: Step;
  observation?: Observation;
  [k: string]: unknown;
}
export interface Step {
  name?: Name;
  hide?: Hide;
  [k: string]: unknown;
}
export interface Observation {
  [k: string]: unknown;
}
