/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OpenFilesResponse = OpenFilesResponse1;
export type MsgType = string;
export type Openfiles = string[];

export interface OpenFilesResponse1 {
  msg_type?: MsgType;
  openFiles: Openfiles;
  [k: string]: unknown;
}
