/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RenameDirectory = RenameDirectory1;
export type Path = string;
export type NewPath = string;

export interface RenameDirectory1 {
  path: Path;
  new_path: NewPath;
  [k: string]: unknown;
}
