from ..llm.openai import OpenAI
import time
from dotenv import load_dotenv
import os

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")

long_prompt = "Repeat after me:" + """I pledge united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
I pledge allegianc to the flag of the united states of america, and to the republic etc...
""" * 10 + """
(repeat just once):
"""

short_prompt = """Repeat after me:

I pledge allegianc to the flag of the united states of america, and to the republic etc...

(repeat just once):"""

long_completion = """Repeat after me:

I pledge allegianc to the flag of the united states of america, and to the republic etc...

(repeat this line exactly 50 times. Do not stop until you have done so.):
"""

if __name__ == "__main__":
    oai = OpenAI(api_key=openai_api_key)

    print(oai.complete(long_prompt))
    print(oai.complete(short_prompt))
    print(oai.complete(long_completion))
