/* tslint:disable */
/* eslint-disable */
/**
 * Continue API
 * Continue API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileEdit } from './FileEdit';
import {
    FileEditFromJSON,
    FileEditFromJSONTyped,
    FileEditToJSON,
} from './FileEdit';

/**
 * 
 * @export
 * @interface EditResp
 */
export interface EditResp {
    /**
     * 
     * @type {Array<FileEdit>}
     * @memberof EditResp
     */
    completion: Array<FileEdit>;
}

/**
 * Check if a given object implements the EditResp interface.
 */
export function instanceOfEditResp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "completion" in value;

    return isInstance;
}

export function EditRespFromJSON(json: any): EditResp {
    return EditRespFromJSONTyped(json, false);
}

export function EditRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditResp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completion': ((json['completion'] as Array<any>).map(FileEditFromJSON)),
    };
}

export function EditRespToJSON(value?: EditResp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completion': ((value.completion as Array<any>).map(FileEditToJSON)),
    };
}

