/* tslint:disable */
/* eslint-disable */
/**
 * Continue API
 * Continue API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExplainResponse
 */
export interface ExplainResponse {
    /**
     * 
     * @type {string}
     * @memberof ExplainResponse
     */
    completion: string;
}

/**
 * Check if a given object implements the ExplainResponse interface.
 */
export function instanceOfExplainResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "completion" in value;

    return isInstance;
}

export function ExplainResponseFromJSON(json: any): ExplainResponse {
    return ExplainResponseFromJSONTyped(json, false);
}

export function ExplainResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExplainResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'completion': json['completion'],
    };
}

export function ExplainResponseToJSON(value?: ExplainResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'completion': value.completion,
    };
}

