/* tslint:disable */
/* eslint-disable */
/**
 * Continue API
 * Continue API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FilePosition } from './FilePosition';
import {
    FilePositionFromJSON,
    FilePositionFromJSONTyped,
    FilePositionToJSON,
} from './FilePosition';

/**
 * A failing test body.
 * @export
 * @interface FailingTestBody
 */
export interface FailingTestBody {
    /**
     * 
     * @type {string}
     * @memberof FailingTestBody
     */
    description: string;
    /**
     * 
     * @type {FilePosition}
     * @memberof FailingTestBody
     */
    fp: FilePosition;
}

/**
 * Check if a given object implements the FailingTestBody interface.
 */
export function instanceOfFailingTestBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "fp" in value;

    return isInstance;
}

export function FailingTestBodyFromJSON(json: any): FailingTestBody {
    return FailingTestBodyFromJSONTyped(json, false);
}

export function FailingTestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailingTestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'fp': FilePositionFromJSON(json['fp']),
    };
}

export function FailingTestBodyToJSON(value?: FailingTestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'fp': FilePositionToJSON(value.fp),
    };
}

