/* tslint:disable */
/* eslint-disable */
/**
 * Continue API
 * Continue API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * A position in a file.
 * @export
 * @interface FilePosition
 */
export interface FilePosition {
    /**
     * 
     * @type {string}
     * @memberof FilePosition
     */
    filecontents: string;
    /**
     * 
     * @type {number}
     * @memberof FilePosition
     */
    lineno: number;
}

/**
 * Check if a given object implements the FilePosition interface.
 */
export function instanceOfFilePosition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "filecontents" in value;
    isInstance = isInstance && "lineno" in value;

    return isInstance;
}

export function FilePositionFromJSON(json: any): FilePosition {
    return FilePositionFromJSONTyped(json, false);
}

export function FilePositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilePosition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'filecontents': json['filecontents'],
        'lineno': json['lineno'],
    };
}

export function FilePositionToJSON(value?: FilePosition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'filecontents': value.filecontents,
        'lineno': value.lineno,
    };
}

