/* tslint:disable */
/* eslint-disable */
/**
 * Continue API
 * Continue API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FindBody
 */
export interface FindBody {
    /**
     * 
     * @type {string}
     * @memberof FindBody
     */
    traceback: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FindBody
     */
    filesystem: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof FindBody
     */
    description?: string;
}

/**
 * Check if a given object implements the FindBody interface.
 */
export function instanceOfFindBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "traceback" in value;
    isInstance = isInstance && "filesystem" in value;

    return isInstance;
}

export function FindBodyFromJSON(json: any): FindBody {
    return FindBodyFromJSONTyped(json, false);
}

export function FindBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'traceback': json['traceback'],
        'filesystem': json['filesystem'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function FindBodyToJSON(value?: FindBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'traceback': value.traceback,
        'filesystem': value.filesystem,
        'description': value.description,
    };
}

