# GitHub Actions Workflow to compile the extension and `npm run package`

name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19.0.0
      - run: npm ci
      - run: npm run clientgen
      - run: npm run compile
      - run: cd react-app && npm install && npm run build
      - run: npm run package
      - name: Save build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-extension
          path: build/*.vsix
